### ISSUE TITLE
URL Question

### ISSUE THREAD

**Issue by jcasimir** [turingschool-projects/omniauth-census#4]
The issue about hard-coding the URL in the code can be handled a few different ways.

I'm thinking about this section of the README: https://github.com/turingschool-projects/omniauth-census#step-2-configure-omniauth

I think the key is to using the `option` mentioned here:

https://github.com/omniauth/omniauth/blob/master/lib/omniauth/strategy.rb

But I don't quite follow the code/docs without poking around myself. This could be a good question to bring up with a mentor in a pairing session. Or look at some other omniauth strategies, particularly some of the complex ones, and see how they handle configurable options.

**Comment by srt32** [comment]
Closing as stale. Feel free to reopen if it's still an active issue.
